#!/usr/bin/env bash

# Simple script which used integrify to locate duplicate files within a directory
# Tested on Darwin 16.4.0 (macOS Sierra 10.12.x)

input_dir="$1"
datestamp=$(date +'%s')
integ_all_list="/tmp/${datestamp}_all_$$.integ"
integ_dup_list="/tmp/${datestamp}_dup_$$.integ"

echo "tmpfile: $integ_all_list"
echo "dupfile: $integ_dup_list"


find "$input_dir" -type f -print0  | xargs -0 integrify -l | sort | tee "$integ_all_list" | awk '{print $1}'| uniq -d > "$integ_dup_list"

duplicates_list=$(cat "$integ_dup_list")

IFS=$'\n';
set -f;
for checksum in "$duplicates_list"; do
  if [ -n "$checksum" ]; then
    grep "$checksum" "$integ_all_list"
  fi
done;
set +f;
unset IFS

rm -f "$integ_all_list" "$integ_dup_list"
